FROM postgres

ENV POSTGRES_HOST=172.31.208.1
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234
ENV POSTGRES_DB=hms
EXPOSE 5432

# the above goes with the command: docker run --name hms-postgres -e POSTGRES_PASSWORD=password -d -p 5432:5432 postgres:alpine